services:
  glpi-help-desk-agent:
    container_name: glpi-help-desk-agent
    build:
      context: ./help-desk-agent
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      GLPI_AGENT_HOST: 0.0.0.0
      GLPI_AGENT_PORT: 8004
    working_dir: /app/help-desk-agent
    command: uv run app.py
    volumes:
      - ./help-desk-agent:/app/help-desk-agent
    networks:
      - quorium-network

  glpi-departments-support-agent:
    container_name: glpi-departments-support-agent
    build:
      context: ./departments-support-agent
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      GLPI_AGENT_HOST: 0.0.0.0
      GLPI_AGENT_PORT: 8005
    working_dir: /app/departments-support-agent
    command: uv run app.py
    volumes:
      - ./departments-support-agent:/app/departments-support-agent
    networks:
      - quorium-network

  glpi-web:
    container_name: glpi-web
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      BACKEND_URL: http://glpi-help-desk-agent:8004
      BACKEND_KB_URL: http://glpi-departments-support-agent:8005
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "250"
      WATCHPACK_POLLING: "true"
      WATCHPACK_POLLING_INTERVAL: "250"
      NEXT_WEBPACK_USEPOLLING: "1"
    command: npm run dev -- --hostname 0.0.0.0 --port 3005
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - glpi-help-desk-agent
      - glpi-departments-support-agent
    networks:
      - quorium-network

networks:
  quorium-network:
    external: true
